/*
* YouTube 自动翻译修复
* 修复 YouTube iOS 客户端自动翻译加载失败的问题
* 版本: 2025-09-03
* 作者: Lofiey
*/

let body = $response.body;

if (body) {
    body = JSON.parse(body);

    if (body.playabilityStatus && body.playabilityStatus.status === "OK") {
        if (body.captions && body.captions.playerCaptionsTracklistRenderer) {
            const tracks = body.captions.playerCaptionsTracklistRenderer.captionTracks;
            if (tracks && tracks.length > 0) {
                // 检查是否有自动生成的字幕
                const autoGeneratedTracks = tracks.filter(track => track.kind === "asr");
                if (autoGeneratedTracks.length > 0) {
                    // 找到了自动字幕，不做任何修改
                    $done({body: JSON.stringify(body)});
                    return;
                }

                // 如果没有自动字幕，从其他来源尝试获取
                if (body.playabilityStatus.playerLegacyDesktopRenderer) {
                    const legacyCaptions = body.playabilityStatus.playerLegacyDesktopRenderer.playerCaptionsTracklistRenderer;
                    if (legacyCaptions && legacyCaptions.captionTracks && legacyCaptions.captionTracks.length > 0) {
                        body.captions.playerCaptionsTracklistRenderer.captionTracks = legacyCaptions.captionTracks;
                    }
                }
            }
        }
    }

    $done({body: JSON.stringify(body)});
} else {
    $done({});
}
